// devfile.js — installs a dev-mode launcher into the StreamDock plugins directory.
// The launcher runs the development source directly; StreamDock's crash-restart
// logic re-invokes it on every exit so changes take effect without a manual app restart.
// ⚠  StreamDock allows ~50 consecutive plugin restarts per session.
const path = require('path');
const os = require('os');
const fs = require('fs');
const { execSync } = require('child_process');

const parentDir = path.resolve(__dirname, '..');
const PluginName = path.basename(parentDir);
const pluginsRoot = process.platform === 'darwin'
    ? path.join(os.homedir(), 'Library/Application Support/HotSpot/StreamDock/plugins')
    : path.join(process.env.APPDATA, 'HotSpot/StreamDock/plugins');
const PluginPath = path.join(pluginsRoot, PluginName);

const skip = [
    path.join('plugin', 'node_modules'),
    path.join('plugin', 'index.js'),
    path.join('plugin', 'autofile.js'),
    path.join('plugin', 'devfile.js'),
    path.join('plugin', 'package.json'),
    path.join('plugin', 'package-lock.json'),
    path.join('plugin', 'pnpm-lock.yaml'),
    path.join('plugin', 'yarn.lock'),
    path.join('plugin', 'build'),
    path.join('plugin', 'log'),
    '.git',
    '.vscode'
];

// Embed the system node path and dev source path at script-run time so the
// launcher always uses the developer's own Node binary, not StreamDock's.
const nodeExe = process.execPath.replaceAll('\\', '\\\\');
const srcIndex = path.resolve(__dirname, 'index.js').replaceAll('\\', '\\\\');
const srcDir = __dirname.replaceAll('\\', '\\\\');

// Launcher written to PluginPath/plugin/index.js.
// It tracks the restart count in .dev-restarts so devfile.js can warn when
// the StreamDock 50-restart limit is approached.
const launcherContent = `// Dev launcher — regenerated by npm run dev, do not edit manually.
// Runs the development source directly; exits so StreamDock restarts it on each change.
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const counterFile = path.join(__dirname, '.dev-restarts');
let restartCount = 0;
try { restartCount = parseInt(fs.readFileSync(counterFile, 'utf8').trim(), 10) || 0; } catch {}
restartCount++;
try { fs.writeFileSync(counterFile, String(restartCount), 'utf8'); } catch {}

const ret = spawnSync('${nodeExe}', ['${srcIndex}', ...process.argv.slice(2)], {
  stdio: 'inherit',
  windowsHide: true,
  cwd: '${srcDir}'
});
process.exit(ret.status ?? 1);
`;

function copyRecursive(src, dest, filter) {
    const stat = fs.statSync(src);
    if (stat.isDirectory()) {
        fs.mkdirSync(dest, { recursive: true });
        for (const entry of fs.readdirSync(src)) {
            const srcEntry = path.join(src, entry);
            const destEntry = path.join(dest, entry);
            if (!filter || filter(srcEntry)) {
                copyRecursive(srcEntry, destEntry, filter);
            }
        }
    } else {
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.copyFileSync(src, dest);
    }
}

// Check the restart counter written by the previous dev-launcher session.
// Warn the developer before they notice the plugin silently stopped.
const counterFile = path.join(PluginPath, 'plugin', '.dev-restarts');
try {
    const prevCount = parseInt(fs.readFileSync(counterFile, 'utf8').trim(), 10) || 0;
    if (prevCount >= 50) {
        console.warn(`⚠  Plugin restart count: ${prevCount}/50 — StreamDock has stopped restarting the plugin.`);
        console.warn('   Please restart the StreamDock app to reset the counter, then run "npm run dev" again.');
    } else if (prevCount >= 45) {
        console.warn(`⚠  Plugin restart count: ${prevCount}/50 — approaching the StreamDock limit.`);
        console.warn('   Restart the StreamDock app soon if the plugin stops responding.');
    }
} catch { /* counter file not yet created — first dev run, nothing to warn about */ }

try {
    // 1. Sync plugin assets (same filter as autofile.js, no bundle)
    copyRecursive(parentDir, PluginPath, (src) => {
        const rel = path.relative(parentDir, src);
        return !skip.some(s => rel === s || rel.startsWith(s + path.sep));
    });

    // 2. Write the dev launcher into the installed plugin's plugin/ folder
    fs.mkdirSync(path.join(PluginPath, 'plugin'), { recursive: true });
    fs.writeFileSync(path.join(PluginPath, 'plugin', 'index.js'), launcherContent, 'utf8');

    // Reset the counter so the new launcher session starts from 0
    fs.writeFileSync(counterFile, '0', 'utf8');

    // 3. Kill the currently running plugin process so StreamDock auto-restarts it
    let killed = false;
    if (process.platform === 'win32') {
        try {
            const out = execSync(
                `powershell -NoProfile -Command "$p = @(Get-CimInstance Win32_Process | Where-Object { $_.Name -eq 'node.exe' -and $_.CommandLine -like '*${PluginName}*' }); $p | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }; $p.Count"`,
                { encoding: 'utf8' }
            );
            killed = parseInt(out.trim(), 10) > 0;
        } catch { /* powershell error */ }
    } else {
        try {
            execSync(`pkill -f "${PluginName}"`, { stdio: 'ignore' });
            killed = true;
        } catch { /* nothing to kill */ }
    }
    if (killed) console.log('Previous plugin process terminated.');

    console.log(`Dev launcher installed to "${PluginPath}"`);
    console.log('StreamDock will restart the plugin with your latest source automatically.');
    console.log('Run npm run dev again after each backend change to reload.');
    console.log('⚠  StreamDock allows ~50 consecutive plugin restarts per session.');
} catch (err) {
    console.error('devfile.js error:', err);
    process.exit(1);
}
